tinymce.addI18n('no',{
"Cut": "Klipp",
"Heading 5": "Overskrift 5",
"Header 2": "Overskrift 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Din nettleser støtter ikke direkte adgang til utklippstavlen. Benytt Ctrl+X\/C\/ tastatur snarvei i stedet for.",
"Heading 4": "Overskrift 4",
"Div": "Div",
"Heading 2": "Overskrift 2",
"Paste": "Lim inn",
"Close": "Steng",
"Font Family": "Skrifttype",
"Pre": "Pre",
"Align right": "Høyrejustert",
"New document": "Nytt dokument",
"Blockquote": "Innrykning",
"Numbered list": "Nummerering",
"Heading 1": "Overskrift 1",
"Headings": "Overskrifter",
"Increase indent": "Øk innrykk",
"Formats": "Formater",
"Headers": "Overskrifter",
"Select all": "Velg alle",
"Header 3": "Overskrift 3",
"Blocks": "Blokker",
"Undo": "Angre",
"Strikethrough": "Gjennom",
"Bullet list": "Punkt tegn",
"Header 1": "Overskrift 1",
"Superscript": "Hevet",
"Clear formatting": "Nullstill formatering",
"Font Sizes": "Skriftstørrelse",
"Subscript": "Senket",
"Header 6": "Overskrift 6",
"Redo": "Gjøre om",
"Paragraph": "Avsnitt",
"Ok": "Ok",
"Bold": "Uthevet",
"Code": "Kode",
"Italic": "Kursiv",
"Align center": "Sentrert",
"Header 5": "Overskrift 5",
"Heading 6": "Overskrift 6",
"Heading 3": "Overskrift 3",
"Decrease indent": "Mink innrykk",
"Header 4": "Overskrift 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Sett inn er innstilt til å innsettes som ren tekst. Innhold blir nå innsatt uten formatering inntil du endrer innstillingen.",
"Underline": "Understrek",
"Cancel": "Avbryte",
"Justify": "Rettferdiggjøre",
"Inline": "På linje",
"Copy": "Kopier",
"Align left": "Venstrejustert",
"Visual aids": "Visuelle hjelpemidler",
"Lower Greek": "Nedre Gresk",
"Square": "Kvadrat",
"Default": "Standard",
"Lower Alpha": "Nedre Alpha",
"Circle": "Sirkel",
"Disc": "Disk",
"Upper Alpha": "Øvre Alpha",
"Upper Roman": "Øvre Roman",
"Lower Roman": "Nedre Roman",
"Name": "Navn",
"Anchor": "Anker",
"You have unsaved changes are you sure you want to navigate away?": "Du har ulagrede endringer. Er du sikker på at du vil fortsette?",
"Restore last draft": "Gjenopprett siste kladd",
"Special character": "Spesielle tegn",
"Source code": "Kildekode",
"B": "B",
"R": "R",
"G": "G",
"Color": "Farge",
"Right to left": "Høyre til venstre",
"Left to right": "Venstre til høyre",
"Emoticons": "Uttrykksikoner",
"Robots": "Roboter",
"Document properties": "Dokument egenskaper",
"Title": "Tittel",
"Keywords": "Søkeord",
"Encoding": "Kodning",
"Description": "Beskrivelse",
"Author": "Forfatter",
"Fullscreen": "Full skjerm",
"Horizontal line": "Horisontal linje",
"Horizontal space": "Horisontal plass",
"Insert\/edit image": "Sett inn\/endre bilde",
"General": "Generellt",
"Advanced": "Avansert",
"Source": "Kilde",
"Border": "Ramme",
"Constrain proportions": "Begrens størrelsesforhold",
"Vertical space": "Vertikal plass",
"Image description": "Bilde beskrivelse",
"Style": "Stil",
"Dimensions": "Dimensjoner",
"Insert image": "Sett inn bilde",
"Zoom in": "Zoom inn",
"Contrast": "Kontrast",
"Back": "Tilbake",
"Gamma": "Gamma",
"Flip horizontally": "Vend horisontalt",
"Resize": "Endre størrelse",
"Sharpen": "Gjør skarpere",
"Zoom out": "Zoom ut",
"Image options": "Bilde innstillinger",
"Apply": "Annvende",
"Brightness": "Lysstyrke",
"Rotate clockwise": "Roter med klokken",
"Rotate counterclockwise": "Roter mot klokken",
"Edit image": "Rediger bilde",
"Color levels": "Fargenivå",
"Crop": "Beskjer",
"Orientation": "Retning",
"Flip vertically": "Vend vertikalt",
"Invert": "Inverter",
"Insert date\/time": "Sett inn dato\/klokkeslett",
"Remove link": "Fjern link",
"Url": "Url",
"Text to display": "Tekst som skal vises",
"Anchors": "Ankre",
"Insert link": "Sett inn link",
"New window": "Nytt vindu",
"None": "Ingen",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Nettadressen du skrev synes å være en ekstern lenke. Ønsker du å legge til det nødvendige  http:prefiks\/\/ ?",
"Target": "Mål",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Nettadressen du skrev synes å være en e-postadresse. Ønsker du å legge inn det nødvendige mailto:? Prefikset ",
"Insert\/edit link": "Sett inn\/endre link",
"Insert\/edit video": "Sett inn\/endre video",
"Poster": "Poster",
"Alternative source": "Alternativ kilde",
"Paste your embed code below:": "Lim inn koden under:",
"Insert video": "Sett inn video",
"Embed": "Embed",
"Nonbreaking space": "Fast mellomrom",
"Page break": "Sideskift",
"Paste as text": "Sett inn som ren tekst",
"Preview": "Forhåndsvisning",
"Print": "Skriv ut",
"Save": "Lagre",
"Could not find the specified string.": "Kunne ikke finne den angitte søketekst",
"Replace": "Erstatte",
"Next": "Neste",
"Whole words": "Hele ord",
"Find and replace": "Finn og erstatt",
"Replace with": "Erstatt med",
"Find": "Finn",
"Replace all": "Erstatt alt",
"Match case": "STORE og små bokstaver",
"Prev": "Forrige",
"Spellcheck": "Stavekontroll",
"Finish": "Ferdig",
"Ignore all": "Ignorer alt",
"Ignore": "Ignorer",
"Add to Dictionary": "Legg til ordbog",
"Insert row before": "Sett inn rad før",
"Rows": "Rekker",
"Height": "Høyde",
"Paste row after": "Lim inn rad etter",
"Alignment": "Tilpasning",
"Border color": "Kant farge",
"Column group": "Kolonne gruppe",
"Row": "Rekke",
"Insert column before": "Sett inn kolonne før",
"Split cell": "Split celle",
"Cell padding": "Celle padding",
"Cell spacing": "Celle avstand",
"Row type": "Rekke type",
"Insert table": "Sett inn tabel",
"Body": "Kropp",
"Caption": "Tekst",
"Footer": "Ende tekst",
"Delete row": "Slett rekke",
"Paste row before": "Sett inn rekke før",
"Scope": "Omfang",
"Delete table": "Slett tabell",
"H Align": "H juster",
"Top": "Topp",
"Header cell": "Top tekst celle",
"Column": "Kolonne",
"Row group": "Rekke gruppe",
"Cell": "Celle",
"Middle": "Midten",
"Cell type": "Celle type",
"Copy row": "Kopier rekke",
"Row properties": "Rekke egenskaper",
"Table properties": "Tabell egenskaper",
"Bottom": "Bunn",
"V Align": "V juster",
"Header": "Topp tekst",
"Right": "Høyre",
"Insert column after": "Sett inn kolonne etter",
"Cols": "Kolonne",
"Insert row after": "Sett inn rekke etter",
"Width": "Bredde",
"Cell properties": "Celle egenskaper",
"Left": "Venstre",
"Cut row": "Klipp rekke",
"Delete column": "Slett kolonne",
"Center": "Sentrering",
"Merge cells": "Slå sammen celler",
"Insert template": "Sett inn mal",
"Templates": "Mal",
"Background color": "Bakgrunnsfarge",
"Custom...": "Brukerdefinert...",
"Custom color": "Brukerdefinert farge",
"No color": "Ingen farge",
"Text color": "Tekst farge",
"Show blocks": "Vis blokker",
"Show invisible characters": "Vis usynlige tegn",
"Words: {0}": "Ord: {0}",
"Insert": "Sett inn",
"File": "Fil",
"Edit": "Rediger",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text område. Trykk ALT-F9 for meny. Trykk ALT-F10 for verktøylinje. Tryk ALT-0 for hjelp",
"Tools": "Verktøy",
"View": "Vis",
"Table": "Tabell",
"Format": "Format"
});